set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN P15 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]


set_property PACKAGE_PIN V1 [get_ports btn_confirm]
set_property IOSTANDARD LVCMOS33 [get_ports btn_confirm]

set_property PACKAGE_PIN R11 [get_ports btn_exit]
set_property IOSTANDARD LVCMOS33 [get_ports btn_exit]


set_property PACKAGE_PIN R1 [get_ports {command[0]}]
set_property PACKAGE_PIN N4 [get_ports {command[1]}]
set_property PACKAGE_PIN M4 [get_ports {command[2]}]
set_property PACKAGE_PIN R2 [get_ports {command[3]}]
set_property PACKAGE_PIN P2 [get_ports {command[4]}]
set_property PACKAGE_PIN P3 [get_ports {command[5]}]
set_property PACKAGE_PIN P4 [get_ports {command[6]}]
set_property PACKAGE_PIN P5 [get_ports {command[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {command[*]}]

set_property PACKAGE_PIN N5 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]

set_property PACKAGE_PIN T4 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

set_property PACKAGE_PIN B4 [get_ports {dk1_segments[0]}]
set_property PACKAGE_PIN A4 [get_ports {dk1_segments[1]}]
set_property PACKAGE_PIN A3 [get_ports {dk1_segments[2]}]
set_property PACKAGE_PIN B1 [get_ports {dk1_segments[3]}]
set_property PACKAGE_PIN A1 [get_ports {dk1_segments[4]}]
set_property PACKAGE_PIN B3 [get_ports {dk1_segments[5]}]
set_property PACKAGE_PIN B2 [get_ports {dk1_segments[6]}]
set_property PACKAGE_PIN D5 [get_ports {dk1_segments[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dk1_segments[*]}]

set_property PACKAGE_PIN D4 [get_ports {dk2_segments[0]}]
set_property PACKAGE_PIN E3 [get_ports {dk2_segments[1]}]
set_property PACKAGE_PIN D3 [get_ports {dk2_segments[2]}]
set_property PACKAGE_PIN F4 [get_ports {dk2_segments[3]}]
set_property PACKAGE_PIN F3 [get_ports {dk2_segments[4]}]
set_property PACKAGE_PIN E2 [get_ports {dk2_segments[5]}]
set_property PACKAGE_PIN D2 [get_ports {dk2_segments[6]}]
set_property PACKAGE_PIN H2 [get_ports {dk2_segments[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dk2_segments[*]}]

set_property PACKAGE_PIN G2 [get_ports {dk_digit_select[0]}]
set_property PACKAGE_PIN C2 [get_ports {dk_digit_select[1]}]
set_property PACKAGE_PIN C1 [get_ports {dk_digit_select[2]}]
set_property PACKAGE_PIN H1 [get_ports {dk_digit_select[3]}]
set_property PACKAGE_PIN G1 [get_ports {dk_digit_select[4]}]
set_property PACKAGE_PIN F1 [get_ports {dk_digit_select[5]}]
set_property PACKAGE_PIN E1 [get_ports {dk_digit_select[6]}]
set_property PACKAGE_PIN G6 [get_ports {dk_digit_select[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dk_digit_select[*]}]


set_property PACKAGE_PIN K2 [get_ports {ld2[0]}]
set_property PACKAGE_PIN J2 [get_ports {ld2[1]}]
set_property PACKAGE_PIN J3 [get_ports {ld2[2]}]
set_property PACKAGE_PIN H4 [get_ports {ld2[3]}]
set_property PACKAGE_PIN J4 [get_ports {ld2[4]}]
set_property PACKAGE_PIN G3 [get_ports {ld2[5]}]
set_property PACKAGE_PIN G4 [get_ports {ld2[6]}]
set_property PACKAGE_PIN F6 [get_ports {ld2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ld2[*]}]

set_property PACKAGE_PIN K3 [get_ports {led[0]}]
set_property PACKAGE_PIN M1 [get_ports {led[1]}]
set_property PACKAGE_PIN L1 [get_ports {led[2]}]
set_property PACKAGE_PIN K6 [get_ports {led[3]}]
set_property PACKAGE_PIN J5 [get_ports {led[4]}]
set_property PACKAGE_PIN H5 [get_ports {led[5]}]
set_property PACKAGE_PIN H6 [get_ports {led[6]}]
set_property PACKAGE_PIN K1 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]

set_property IOSTANDARD LVCMOS33 [get_ports {scalar_command[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scalar_command[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scalar_command[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scalar_command[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scalar_command[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scalar_command[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scalar_command[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scalar_command[0]}]
set_property PACKAGE_PIN T5 [get_ports {scalar_command[0]}]
set_property PACKAGE_PIN T3 [get_ports {scalar_command[1]}]
set_property PACKAGE_PIN R3 [get_ports {scalar_command[2]}]
set_property PACKAGE_PIN V4 [get_ports {scalar_command[3]}]
set_property PACKAGE_PIN V5 [get_ports {scalar_command[4]}]
set_property PACKAGE_PIN V2 [get_ports {scalar_command[5]}]
set_property PACKAGE_PIN U2 [get_ports {scalar_command[6]}]
set_property PACKAGE_PIN U3 [get_ports {scalar_command[7]}]
